[package]
edition = "2021"
license = "GPL-3.0"
name = "desktop_objc"
version = "0.0.0"
publish = false

[features]
default = []

[dependencies]
anyhow = "=1.0.86"
thiserror = "=1.0.61"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "=0.9.4"

[build-dependencies]
cc = "1.0.104"
